Sprint 1/step 2
antgrakhov/react-burger pull request #2
Opened 2023-08-06 12:51 UTC by antgrakhov

Финальная сдача работы в sprint-1

2023-08-06 20:38 UTC, andryxxa93 requested changes
Необходимо исправить:
- Добавьте проверку ответа сервера - res.ok

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-08-06 20:38 UTC, andryxxa93 commented on src/components/app/app.jsx
> +        fetch(dataUrl)
**Можно лучше**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}

```

и разместить их в отдельном файле  `utils/burger-api.js`, а не описывать запросы в самом компоненте

2023-08-06 20:38 UTC, andryxxa93 commented on src/components/app/app.jsx
> +            .then(res => res.json())
**Надо исправить**
Добавьте проверку ответа сервера - res.ok:

Например:

```
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответи не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

`fetch(someUrl).then(checkReponse)`

2023-08-06 20:38 UTC, andryxxa93 commented on src/components/modal/modal.jsx
> +            document.removeEventListener('keydown', handleEscPressed);
**Отлично!**
Вы сделали отписку от слушателя, это позволит избежать утечек памяти.

2023-08-07 07:31 UTC, antgrakhov commented on src/components/app/app.jsx
> +        fetch(dataUrl)
Поправил

2023-08-07 07:31 UTC, antgrakhov commented on src/components/app/app.jsx
> +            .then(res => res.json())
Поправил

2023-08-07 20:55 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-08-07 21:02 UTC, merged